// packages/site/src/App.vue
<script setup lang="ts">
import Editor from './components/Editor.vue'
import { ref, onMounted } from 'vue'

const editorRef = ref()
const templates = ref<any[]>([])
const currentTemplateName = ref('')

const TEMPLATE_STORAGE_KEY = 'editor-templates';

onMounted(() => {
  const savedTemplates = localStorage.getItem(TEMPLATE_STORAGE_KEY);
  if (savedTemplates) {
    templates.value = JSON.parse(savedTemplates);
    if (templates.value.length > 0) {
      loadTemplate(templates.value[0]);
    }
  }
});

const addBlock = () => {
  editorRef.value.editor.addBlock();
}

const saveTemplate = () => {
  const data = editorRef.value.editor.getData();
  console.log('data', data);
  
  const name = prompt('请输入模板名称：', `模板${templates.value.length + 1}`);
  if (name) {
    templates.value.push({ name, data });
    currentTemplateName.value = name;
    localStorage.setItem(TEMPLATE_STORAGE_KEY, JSON.stringify(templates.value));
  }
}

const loadTemplate = (template: any) => {
  console.log('template', template, template.data);
  
  currentTemplateName.value = template.name;
  // 销毁并重新创建 editor 实例来加载模板
  editorRef.value.recreateEditor(template.data);
}

const printData = () => {
  const data = editorRef.value.editor.getData();
  console.log('data', data);
}
</script>

<template>
  <div class="w-[560px]">
    <div class="flex justify-between mb-4">
      <div>提示词</div>
      <div>
        <button 
          v-for="template in templates" 
          :key="template.name" 
          @click="loadTemplate(template)"
          :class="{ 'font-bold': currentTemplateName === template.name }"
        >
          {{ template.name }}
        </button>
        <i class="ci-save font-size-5" title="保存为模板" @click="saveTemplate"></i>
        |
        <i class="ci-task font-size-5" title="插入编辑块" @click="addBlock"></i>
        |
        <i class="ci-print font-size-5" title="打印编辑器数据" @click="printData"></i>
      </div>
    </div>
    <Editor ref="editorRef" />
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/site-ng/src/app/app.component.ts
import { Component, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { EditorComponent } from './editor/editor.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, EditorComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements AfterViewInit {
  @ViewChild(EditorComponent) editorComponent?: EditorComponent;

  templates: { name: string; data: any }[] = [];
  currentTemplateName = '';

  private readonly TEMPLATE_STORAGE_KEY = 'editor-templates';

  ngAfterViewInit() {
    const savedTemplates = localStorage.getItem(this.TEMPLATE_STORAGE_KEY);
    if (savedTemplates) {
      this.templates = JSON.parse(savedTemplates);
      if (this.templates.length > 0) {
        this.loadTemplate(this.templates[0]);
      }
    }
  }

  addBlock() {
    this.editorComponent?.addBlock();
  }

  saveTemplate() {
    const data = this.editorComponent?.getData();
    const name = window.prompt('请输入模板名称：', `模板${this.templates.length + 1}`);
    if (name && data) {
      this.templates.push({ name, data });
      this.currentTemplateName = name;
      localStorage.setItem(this.TEMPLATE_STORAGE_KEY, JSON.stringify(this.templates));
    }
  }

  loadTemplate(template: { name: string; data: any }) {
    this.currentTemplateName = template.name;
    this.editorComponent?.recreateEditor(template.data);
  }
}

<div class="app">
  <div class="topbar">
    <div class="title">提示词</div>
    <div class="actions">
      <button
        class="template-btn"
        *ngFor="let template of templates"
        (click)="loadTemplate(template)"
        [class.active]="currentTemplateName === template.name"
      >
        {{ template.name }}
      </button>

      <button class="icon-btn" type="button" title="保存为模板" (click)="saveTemplate()">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path>
          <polyline points="17 21 17 13 7 13 7 21"></polyline>
          <polyline points="7 3 7 8 15 8"></polyline>
        </svg>
      </button>

      <span class="sep">|</span>

      <button class="icon-btn" type="button" title="插入编辑块" (click)="addBlock()">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <rect x="3" y="3" width="7" height="7"></rect>
          <rect x="14" y="3" width="7" height="7"></rect>
          <rect x="14" y="14" width="7" height="7"></rect>
          <rect x="3" y="14" width="7" height="7"></rect>
        </svg>
      </button>
    </div>
  </div>

  <app-editor></app-editor>
</div>

<router-outlet />
